const experiences=[['🍜','혼밥','Solo',100],['🎬','혼영','Solo',100],['🍷','혼술','Solo',200],['✈️','해외 혼자 여행','Travel',500],['🏕️','캠핑','Adventure',200],['🤿','스노클링','Adventure',300],['🏄','서핑','Adventure',500],['🎿','스키','Adventure',300],['🏺','도예','Creative',200],['📷','사진','Creative',100],['🎤','콘서트','Culture',200],['🍣','오마카세','Food',200]];
let selected=new Set(JSON.parse(localStorage.getItem('lifexp')||'[]'));
const app=document.querySelector('#app');
function bunny(gear='🤿',kind='water'){return `<div class="rabbit-scene exact-rabbit-scene"><img class="exact-scene-img" src="assets/rabbit-scene.png" alt="LIFE XP 토끼"></div>`}
function landing(){app.innerHTML=`<div class="shell"><section class="hero"><div class="eyebrow">LIFE XP</div><h1>PLAY YOUR LIFE.</h1><p class="muted">지금까지 얼마나 많은 걸 경험했나요?</p>${bunny('🎒','')}<p>현실에서 경험하고, 작은 토끼와 함께<br><b>나의 인생 레벨을 올려보세요.</b></p><div class="space"></div><button class="primary" onclick="test()">내 Life Level 알아보기</button></section></div>`}
function test(){app.innerHTML=`<div class="shell"><div class="eyebrow">EXPERIENCE TEST</div><h1 class="title">해본 걸 골라봐 🐰</h1><p class="muted">정답은 없어. 네가 직접 해봤다면 체크!</p><div class="grid">${experiences.map((e,i)=>`<button class="exp ${selected.has(i)?'selected':''}" onclick="toggle(${i})"><span style="font-size:28px">${e[0]}</span><b>${e[1]}</b><small class="muted">${e[2]} · +${e[3]} XP</small></button>`).join('')}</div><div class="space"></div><button class="primary" onclick="home()">내 결과 보기</button></div>`}
function toggle(i){selected.has(i)?selected.delete(i):selected.add(i);localStorage.setItem('lifexp',JSON.stringify([...selected]));test()}
function stats(){let xp=[...selected].reduce((s,i)=>s+experiences[i][3],0);return {xp,count:selected.size,lv:Math.max(1,Math.floor(xp/400)+1)}}
function home(gear='🤿',label='첫 스노클링 완료!',meta='제주 · 2026.08.18 · +500 XP'){let s=stats();app.innerHTML=`<div class="shell"><div class="card"><div class="top"><div><div class="eyebrow">MY LIFE</div><h1 class="title">Life Lv. ${s.lv}</h1><span class="muted">${s.count} experiences · ${Math.floor(s.count/3)} badges</span></div><div class="xp">${s.xp.toLocaleString()} XP</div></div>${bunny(gear)}<div class="center"><h3>${label}</h3><p class="muted">${meta}</p><div class="chips" style="justify-content:center"><span class="chip">🏆 Ocean Rookie</span><span class="chip">NEW ITEM ${gear}</span></div></div><div class="space"></div><div class="top"><b style="font-size:12px">다음 레벨까지</b><b style="font-size:12px">340 / 500 XP</b></div><div class="progress"><i></i></div></div><h2>What's next?</h2><div class="grid"><button class="exp" onclick="home('🤿','첫 스노클링 완료!','제주 · +500 XP')">🤿<b>스노클링</b><small>완료 · Lv.2</small></button><button class="exp" onclick="home('⛺','캠핑의 밤','가평 · +350 XP')">🏕️<b>캠핑</b><small>완료 · Lv.3</small></button><button class="exp" onclick="home('🏺','도예 첫 경험 완료!','성수 · +400 XP')">🏺<b>도예</b><small>완료 · Lv.1</small></button><button class="exp" onclick="home('🏄','다음 도전: 첫 서핑','아직 경험하지 않았어요 · +700 XP')">🏄<b>서핑</b><small>WANT · +700 XP</small></button></div><div class="card"><div class="eyebrow">NEXT QUEST</div><h3>🏄 First Wave</h3><p class="muted">처음으로 서핑에 도전해보세요.</p><b>Reward · +700 XP</b></div>${nav('home')}</div>`}
function passport(){app.innerHTML=`<div class="shell"><div class="eyebrow">MY LIFE PASSPORT</div><h1 class="title">2026의 경험들</h1><p class="muted">해본 순간들이 작은 도장처럼 쌓여요.</p>${[['🤿','SNORKELING','2026.08.18'],['🏕️','CAMPING','2026.07.04'],['🏺','POTTERY','2026.06.21'],['🎤','CONCERT','2026.05.17']].map(x=>`<div class="stamp"><span class="mini">${x[0]}</span><div><b>${x[1]}</b><div class="muted">${x[2]}</div></div><span style="margin-left:auto">🐰 ✓</span></div>`).join('')}${nav('passport')}</div>`}
function nav(active){return `<nav class="nav"><button onclick="home()">${active==='home'?'● ':''}🏠 Home</button><button onclick="test()">✨ Explore</button><button onclick="passport()">${active==='passport'?'● ':''}📖 Passport</button></nav>`}landing();
